SOURCE = main.c
CC = gcc
COMPILER_FLAGS = -Wall -Wextra -pedantic -std=c11
LINKER_FLAGS = -lSDL2 -lGL
NAME = scroll-and-sigil
main : $(SOURCE)
	$(CC) $(SOURCE) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(NAME)
