#ifndef ASSETS_H
#define ASSETS_H

#define SHADER_SCREEN 0
#define SHADER_TEXTURE_2D 1
#define SHADER_TEXTURE_3D 2
#define SHADER_TEXTURE_3D_COLOR 3
#define SHADER_TEXTURE_3D_SHADOW 4
#define SHADER_SHADOW_PASS 5
#define SHADER_COUNT 6

#define TEXTURE_BARON 0
#define TEXTURE_GRASS 1
#define TEXTURE_PLANK_FLOOR 2
#define TEXTURE_PLANKS 3
#define TEXTURE_STONE 4
#define TEXTURE_STONE_FLOOR 5
#define TEXTURE_COUNT 6

#define MUSIC_VAMPIRE_KILLER 0
#define MUSIC_COUNT 1

#define SOUND_BARON_SCREAM 0
#define SOUND_COUNT 1

#endif
